upgrade dkml-workflows

diff --git a/ci/setup-dkml/gh-linux/pre/action.yml b/ci/setup-dkml/gh-linux/pre/action.yml
--- a/ci/setup-dkml/gh-linux/pre/action.yml
+++ b/ci/setup-dkml/gh-linux/pre/action.yml
@@ -1390,9 +1390,11 @@ runs:
             windows_*)
                 if ! grep -q '\(^|\[\)DiskuvOCamlMSYS2Dir ' ".ci/sd4/setenv.$do_setenv_SWITCH.txt"; then
                     if [ -x /usr/bin/cygpath ]; then
-                        MSYS2_DIR_NATIVE=$(/usr/bin/cygpath -aw "msys64")
+                        MSYS2_DIR_NATIVE=$(/usr/bin/cygpath -aw /)
                     else
-                        MSYS2_DIR_NATIVE="$PWD"
+                        # If we are already inside MSYS2 then MSYSTEM_PREFIX should be set. But cygpath should be there as well!!
+                        echo "FATAL: Could not locate MSYS2: there was no cygpath" >&2
+                        exit 3
                     fi
                     MSYS2_DIR_NATIVE_ESCAPED=$(printf "%s" "$MSYS2_DIR_NATIVE" | sed 's/\\/\\\\/g')
                     opamrun option --switch "$do_setenv_SWITCH" setenv+="DiskuvOCamlMSYS2Dir = \"$MSYS2_DIR_NATIVE_ESCAPED\""
@@ -1564,7 +1566,7 @@ runs:
       shell: bash
       run: |
         set -x
-        echo '54ccd7-${{ inputs.FDOPEN_OPAMEXE_BOOTSTRAP }}-${{ steps.full_matrix_vars.outputs.dkml_host_abi }}-${{ steps.full_matrix_vars.outputs.opam_abi }}-${{ steps.full_matrix_vars.outputs.bootstrap_opam_version }}' > .ci/sd4/cachekey.opam.binaries
+        echo '317446-${{ inputs.FDOPEN_OPAMEXE_BOOTSTRAP }}-${{ steps.full_matrix_vars.outputs.dkml_host_abi }}-${{ steps.full_matrix_vars.outputs.opam_abi }}-${{ steps.full_matrix_vars.outputs.bootstrap_opam_version }}' > .ci/sd4/cachekey.opam.binaries
         echo '${{ steps.full_matrix_vars.outputs.abi_pattern }}-${{ steps.full_matrix_vars.outputs.vsstudio_arch }}-${{ steps.full_matrix_vars.outputs.vsstudio_hostarch }}-${{ steps.full_matrix_vars.outputs.vsstudio_dir }}-${{ steps.full_matrix_vars.outputs.vsstudio_vcvarsver }}-${{ steps.full_matrix_vars.outputs.vsstudio_winsdkver }}-${{ steps.full_matrix_vars.outputs.vsstudio_msvspreference }}-${{ steps.full_matrix_vars.outputs.vsstudio_cmakegenerator }}' > .ci/sd4/cachekey.vsstudio
         echo '${{ inputs.OCAML_COMPILER }}-${{ inputs.DISKUV_OPAM_REPOSITORY }}-${{ inputs.DKML_COMPILER }}-${{ inputs.CONF_DKML_CROSS_TOOLCHAIN }}' > .ci/sd4/cachekey.ci.inputs
 
diff --git a/ci/setup-dkml/gl/setup-dkml.gitlab-ci.yml b/ci/setup-dkml/gl/setup-dkml.gitlab-ci.yml
--- a/ci/setup-dkml/gl/setup-dkml.gitlab-ci.yml
+++ b/ci/setup-dkml/gl/setup-dkml.gitlab-ci.yml
@@ -43,7 +43,7 @@ variables:
 
   # Only 4 caches allowed in GitLab CI
   cache:
-    - key: "1_${CACHE_PREFIX}-313d687-${abi_pattern}-${CI_COMMIT_REF_SLUG}"
+    - key: "1_${CACHE_PREFIX}-bf92f53-${abi_pattern}-${CI_COMMIT_REF_SLUG}"
       paths:
         - .ci/sd4/bs
         - ${opam_root_cacheable}/config
@@ -1462,9 +1462,11 @@ variables:
           windows_*)
               if ! grep -q '\(^|\[\)DiskuvOCamlMSYS2Dir ' ".ci/sd4/setenv.$do_setenv_SWITCH.txt"; then
                   if [ -x /usr/bin/cygpath ]; then
-                      MSYS2_DIR_NATIVE=$(/usr/bin/cygpath -aw "msys64")
+                      MSYS2_DIR_NATIVE=$(/usr/bin/cygpath -aw /)
                   else
-                      MSYS2_DIR_NATIVE="$PWD"
+                      # If we are already inside MSYS2 then MSYSTEM_PREFIX should be set. But cygpath should be there as well!!
+                      echo "FATAL: Could not locate MSYS2: there was no cygpath" >&2
+                      exit 3
                   fi
                   MSYS2_DIR_NATIVE_ESCAPED=$(printf "%s" "$MSYS2_DIR_NATIVE" | sed 's/\\/\\\\/g')
                   opamrun option --switch "$do_setenv_SWITCH" setenv+="DiskuvOCamlMSYS2Dir = \"$MSYS2_DIR_NATIVE_ESCAPED\""
@@ -3125,9 +3127,11 @@ variables:
           windows_*)
               if ! grep -q '\(^|\[\)DiskuvOCamlMSYS2Dir ' ".ci/sd4/setenv.$do_setenv_SWITCH.txt"; then
                   if [ -x /usr/bin/cygpath ]; then
-                      MSYS2_DIR_NATIVE=$(/usr/bin/cygpath -aw "msys64")
+                      MSYS2_DIR_NATIVE=$(/usr/bin/cygpath -aw /)
                   else
-                      MSYS2_DIR_NATIVE="$PWD"
+                      # If we are already inside MSYS2 then MSYSTEM_PREFIX should be set. But cygpath should be there as well!!
+                      echo "FATAL: Could not locate MSYS2: there was no cygpath" >&2
+                      exit 3
                   fi
                   MSYS2_DIR_NATIVE_ESCAPED=$(printf "%s" "$MSYS2_DIR_NATIVE" | sed 's/\\/\\\\/g')
                   opamrun option --switch "$do_setenv_SWITCH" setenv+="DiskuvOCamlMSYS2Dir = \"$MSYS2_DIR_NATIVE_ESCAPED\""
@@ -4668,9 +4672,11 @@ variables:
           windows_*)
               if ! grep -q '\(^|\[\)DiskuvOCamlMSYS2Dir ' ".ci/sd4/setenv.$do_setenv_SWITCH.txt"; then
                   if [ -x /usr/bin/cygpath ]; then
-                      MSYS2_DIR_NATIVE=$(/usr/bin/cygpath -aw "msys64")
+                      MSYS2_DIR_NATIVE=$(/usr/bin/cygpath -aw /)
                   else
-                      MSYS2_DIR_NATIVE="$PWD"
+                      # If we are already inside MSYS2 then MSYSTEM_PREFIX should be set. But cygpath should be there as well!!
+                      echo "FATAL: Could not locate MSYS2: there was no cygpath" >&2
+                      exit 3
                   fi
                   MSYS2_DIR_NATIVE_ESCAPED=$(printf "%s" "$MSYS2_DIR_NATIVE" | sed 's/\\/\\\\/g')
                   opamrun option --switch "$do_setenv_SWITCH" setenv+="DiskuvOCamlMSYS2Dir = \"$MSYS2_DIR_NATIVE_ESCAPED\""
